# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 01:50
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_auto_20170113_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='rest_duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='workout',
            name='sets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=10), default=[], size=10),
        ),
    ]
