# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_exercisehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisehistory',
            old_name='set_weights',
            new_name='weights_per_set',
        ),
    ]
