# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_auto_20170121_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
